jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Bipaa\LdapBundle\Security\User\LdapUser:
            algorithm:        sha1
            encode_as_base64: true
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ldap:
            id: bipaa_ldap.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend:
            provider:               ldap
            pattern:                ^/
            anonymous: ~
            bipaa_ldap: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: _home

    access_control:
        - { path: ^/admin, roles: ROLE_LDAP_LDAP_ADMIN }
        - { path: ^/usercp, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
